### ISSUE TITLE
API /upload

### ISSUE THREAD

**Issue by saluyi** [jack7531/tm-exam-1#2]
Hi @jack7531 

I saw you have done the API /upload.
And seems suit all requirement.
- receive files
- save in local 
- send it to sqs for next action.

Could you try to design some unit test scenario for this.

**Comment by jack7531** [comment]
Hi @saluyi 

I did try to write following unit test with spring boot test this afternoon:
1. receive files
2. save in local
3. unzip zip file

not sure is it in the correct way?
Is any other scenario do I need to try?

**Comment by saluyi** [comment]
Hi @jack7531 ,

I found you made some great integrated tests for your upload API and unzip function.
By these tests, I can understand what test scenario that we have.

There are two suggestions may you can try to use on these test.

1. test case name and test case design
test case name should be meaningful that can be easy to know what we are testing and what we are expected.
So the test Function Name testPostFiles may be changed to "upload_zip_file_then_file_should_be_exist_in_server"

2. test input and result
I recommend to input and result is fixed.
In testUnZip(), we can found the file is the Last Upload File.
So the input and result is always changing.
Maybe sometimes this test is pass or failed.
We would like the test result is not randomly.

3. test result
In testPostFiles(), it test upload zip by API /upload.
And check the latest file is exist or not.
Does it mean the file is really uploaded successfully?

**Comment by saluyi** [comment]
And you can find my email address on my profile.
If there is something is not clear.
We can have a con-call to discuss details.

**Comment by jack7531** [comment]
Hi @saluyi 
Thank you for your suggestions.
And I already send an email to you.
Please check it.

**Comment by jack7531** [comment]
@saluyi 
update: testPostFiles()
determine the file is really uploaded successful by compare both files' sha1.
