### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by saluyi** [jack7531/tm-exam-1#3]
Hi @jack7531 ,

I saw you have enhanced you API and Test.
Could we have an online meeting at 7/31.
We can use https://meet.google.com/.

In this meeting, we will ask some questions about the error handling, SQS, Log, and the Implement details in the application.

**Comment by jack7531** [comment]
@saluyi 
Confirmed.

**Comment by saluyi** [comment]
@jack7531 
Is it okay at 1:30PM?

**Comment by jack7531** [comment]
@saluyi 
Sure.
